# try
# except
# finally
#try block test a block of code
#except handles error
#finally lets you to execute code
'''try:
	print(x)
except:
	print('An exception has occured!')'''
#print(x)
'''try:
	print(x)
except NameError:
	print('varibale x is not defined')
except:
	print('Something went wrong!')'''
try:
	print('hello')
except:
	print('something wrong')
else:
	print('nothing wrong')